### ISSUE TITLE
bwrap: execvp flutter: No such file or directory

### ISSUE THREAD

**Issue by rootmeanclaire** [eshimoniak/flutter-flatpak#1]
Running `flatpak run dev.flutter.Flutter` results in:

```
bwrap: execvp flutter: No such file or directory
```

In b62069b391c98e3c172a4e7ce5d5091cd2da9cba, flutter was able to run long enough to give an error message about a bad `PATH`, so I don't think it's _completely_ broken.

I've probably made a very beginner mistake, but I haven't been able to figure it out yet.

**Comment by prateekmedia** [comment]
Have you added flutter bin to the PATH?

**Comment by rootmeanclaire** [comment]
I think @prateekmedia was right.

It's strange though; changing the `cp -r` command to have a different destination causes the build to fail with `Error: Command 'flutter' not found`, so clearly it was able to be found at some stage in the build process.

Path has been updated in 7eeeba3cc8a15784ad1fbe188237db31d23b193c.
